# This workflow just verifies that the given anchore endpoint is reachable and responsive
#
name: Anchore Enterprise Test

on: 
  #workflow_dispatch
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: '15 21 15 * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Test'  

  
jobs:
  Check-Endpoint:
    runs-on: ubuntu-latest
    env:
      ANCHORE_CLI_USER: ${{ secrets.ANCHORE_CLI_USER }}
      ANCHORE_CLI_PASS: ${{ secrets.ANCHORE_CLI_PASS }}
      ANCHORE_CLI_URL: ${{ secrets.ANCHORE_CLI_URL }}
    steps:
    - name: Ping Endpoint
      run: | 
        curl -u ${ANCHORE_CLI_USER}:${ANCHORE_CLI_PASS} -X 'GET' -H 'accept: application/json' ${ANCHORE_CLI_URL}/status
    - name: Get System Status
      run: | 
        curl -u ${ANCHORE_CLI_USER}:${ANCHORE_CLI_PASS} -X 'GET' -H 'accept: application/json' ${ANCHORE_CLI_URL}/system
